apiVersion: v1
kind: Service
metadata:
  name: ouyang-mysql-master-svc
  labels:
    name: ouyang-mysql-master-svc
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 32308
  selector:
    name: ouyang-mysql-pod-master